FROM python:3.12-slim

WORKDIR /app

COPY frontend_service/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONPATH=/app \
    PYTHONUNBUFFERED=1

COPY frontend_service /app/frontend_service
COPY shared /app/shared

EXPOSE 8004

CMD ["python", "-m", "uvicorn", "frontend_service.app.main:app", "--host", "0.0.0.0", "--port", "8004"]
